# Generated by Django 5.1.7 on 2025-05-02 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen1', models.ImageField(blank=True, null=True, upload_to='publicaciones/')),
                ('imagen2', models.ImageField(blank=True, null=True, upload_to='publicaciones/')),
                ('imagen3', models.ImageField(blank=True, null=True, upload_to='publicaciones/')),
                ('opciones_envio', models.CharField(choices=[('domicilio', 'Domicilio'), ('retiro_local', 'Retiro en local'), ('ambos', 'Ambos')], default='domicilio', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
